### ISSUE TITLE
Unable to Generate Submission Zip

### ISSUE THREAD

**Issue by abhinavrai44** [epic-kitchens/C1-Action-Recognition#1]
Hi, 

When I run create_submission.py I am getting the error -

AttributeError: 'Namespace' object has no attribute 'scores_pt'

I am using the TSM model for testing

Thanks
Abhinav

**Comment by DWhettam** [comment]
Hi @abhinavrai44 
Sorry there was a mistake in the arguments for the submission script. It has been fixed in #2, so I'll close this issue. Please open another issue if you have any other issues. Thanks!

**Comment by abhinavrai44** [comment]
@DWhettam  Thanks.
