### ISSUE TITLE
Can you share the script to compute the metrics on the test set?

### ISSUE THREAD

**Issue by qwangku** [epic-kitchens/C1-Action-Recognition#3]
Thanks for providing these helpful resources.
I found "We provide an evaluation script to compute the metrics we report in the paper on the validation set." part in the readme. 
Can you also share the script and exemplary command to compute the metrics on the test (not validation) set? 

I tried to use EPIC_100_test_timestamps.pkl  to replace EPIC_100_validation.pkl, but got the following error:

Traceback (most recent call last):
  File "evaluate.py", line 127, in <module>
    main(parser.parse_args())
  File "evaluate.py", line 75, in main
    labels = add_action_class_column(labels)
  File "evaluate.py", line 66, in add_action_class_column
    groundtruth_df["verb_class"], groundtruth_df["noun_class"]
  File "/mnt/miniconda/envs/epic-models/lib/python3.8/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/mnt/miniconda/envs/epic-models/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2891, in get_loc
    raise KeyError(key) from err
KeyError: 'verb_class'

**Comment by dimadamen** [comment]
We do not publicly share the ground truth of the test set!! These are hidden behind the Codalab leaderboard.
To evaluate on the test set, you need to submit your results to the test server. Please read all details on how to register and submit here:
http://epic-kitchens.github.io/2022#challenges
The action recognition leaderboard is available at: https://codalab.lisn.upsaclay.fr/competitions/776#results

**Comment by qwangku** [comment]
@dimadamen  Thanks for the response.  It seems https://github.com/epic-kitchens/epic-kitchens-slowfast already provided a command to reproduce the test accuracy results, so I guess there should be a way to do the same to TSM and other models in order to compare the test accuracies. Please let me know if my understanding is wrong.

**Comment by DWhettam** [comment]
@qwangku the slowfast repo gives a command to generate **predictions** on the test set, **not accuracy results**. Both repos use [test_timestamps.csv](https://github.com/epic-kitchens/epic-kitchens-100-annotations/blob/master/EPIC_100_test_timestamps.csv), which does not have any ground truth. As above, if you want to evaluate on the test set you have to submit our Codalab competition.
