### ISSUE TITLE
 if I can still submit a test file for test in EPIC-KITCHENS-100 Action Recognition competition in CodaLab website?

### ISSUE THREAD

**Issue by caomq123** [epic-kitchens/C1-Action-Recognition#4]
Hello, I am a graduate student in computer science and am currently exploring the field of egocentric action recognition, and your Epic-kitchens dataset has given me great space to think and research motivation. Now I want to test my work and would like to ask if I can still submit a test file for test in EPIC-KITCHENS-100 Action Recognition competition in CodaLab website? The decision is pending after the participation module is registered. Look forward to receiving your reply. Thank you.

**Comment by dimadamen** [comment]
As noted here: https://epic-kitchens.github.io/2022#challenges
all the leaderboards are now closed to prepare for the 2023 challenges. All leaderboards will open mid January for the challenges phase, and you can then submit to the test server. 
The participation is paused until then,
